-- MySQL Script generated by MySQL Workbench
-- Thu Dec 27 03:49:39 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Oudleerlingen
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Oudleerlingen` ;

-- -----------------------------------------------------
-- Schema Oudleerlingen
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Oudleerlingen` DEFAULT CHARACTER SET utf8 ;
USE `Oudleerlingen` ;

-- -----------------------------------------------------
-- Table `Oudleerlingen`.`Posts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Oudleerlingen`.`Posts` ;

CREATE TABLE IF NOT EXISTS `Oudleerlingen`.`Posts` (
  `idPosts` INT NOT NULL AUTO_INCREMENT,
  `Ervaringen` VARCHAR(280) NOT NULL,
  `Delen` VARCHAR(280) NOT NULL,
  `Herinneringen_SLCB` VARCHAR(280) NOT NULL,
  PRIMARY KEY (`idPosts`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Oudleerlingen`.`Werk`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Oudleerlingen`.`Werk` ;

CREATE TABLE IF NOT EXISTS `Oudleerlingen`.`Werk` (
  `idWerk` INT NOT NULL AUTO_INCREMENT,
  `Werk` VARCHAR(95) NOT NULL,
  `Bedrijf` VARCHAR(95) NOT NULL,
  `Beginjaar` VARCHAR(45) NOT NULL,
  `Vestiging_bedrijf` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idWerk`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Oudleerlingen`.`Vervolgstudies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Oudleerlingen`.`Vervolgstudies` ;

CREATE TABLE IF NOT EXISTS `Oudleerlingen`.`Vervolgstudies` (
  `idVervolgstudies` INT NOT NULL AUTO_INCREMENT,
  `School_na_SLCB` VARCHAR(90) NOT NULL,
  `Richting` VARCHAR(45) NOT NULL,
  `Diploma` VARCHAR(45) NULL,
  `Afstudeerjaar` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idVervolgstudies`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Oudleerlingen`.`Personen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Oudleerlingen`.`Personen` ;

CREATE TABLE IF NOT EXISTS `Oudleerlingen`.`Personen` (
  `idPersonen` INT NOT NULL AUTO_INCREMENT,
  `Naam` VARCHAR(45) NOT NULL,
  `Familienaam` VARCHAR(45) NOT NULL,
  `Geboortedatum` VARCHAR(20) NOT NULL,
  `E_mail` VARCHAR(45) NULL,
  `Telefoonnummer` VARCHAR(15) NULL,
  `Afstudeerjaar` VARCHAR(45) NOT NULL,
  `Richting_SLCB` VARCHAR(45) NOT NULL,
  `Werk_idWerk` INT NULL,
  `Vervolgstudies_idVervolgstudies` INT NULL,
  `Posts_idPosts` INT NULL,
  PRIMARY KEY (`idPersonen`),
  INDEX `fk_Personen_Werk_idx` (`Werk_idWerk` ASC) VISIBLE,
  INDEX `fk_Personen_Vervolgstudies1_idx` (`Vervolgstudies_idVervolgstudies` ASC) VISIBLE,
  INDEX `fk_Personen_Posts1_idx` (`Posts_idPosts` ASC) VISIBLE,
  CONSTRAINT `fk_Personen_Werk`
    FOREIGN KEY (`Werk_idWerk`)
    REFERENCES `Oudleerlingen`.`Werk` (`idWerk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Personen_Vervolgstudies1`
    FOREIGN KEY (`Vervolgstudies_idVervolgstudies`)
    REFERENCES `Oudleerlingen`.`Vervolgstudies` (`idVervolgstudies`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Personen_Posts1`
    FOREIGN KEY (`Posts_idPosts`)
    REFERENCES `Oudleerlingen`.`Posts` (`idPosts`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- MySQL dump 10.13  Distrib 8.0.13, for Win64 (x86_64)
--
-- Host: 127.0.0.1    Database: oudleerlingen
-- ------------------------------------------------------
-- Server version	8.0.13

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
 SET NAMES utf8 ;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Table structure for table `personen`
--

DROP TABLE IF EXISTS `personen`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
 SET character_set_client = utf8mb4 ;
CREATE TABLE `personen` (
  `idPersonen` int(11) NOT NULL AUTO_INCREMENT,
  `Naam` varchar(45) NOT NULL,
  `Familienaam` varchar(45) NOT NULL,
  `Geboortedatum` varchar(20) NOT NULL,
  `E_mail` varchar(45) DEFAULT NULL,
  `Telefoonnummer` varchar(15) DEFAULT NULL,
  `Afstudeerjaar` varchar(45) NOT NULL,
  `Richting_SLCB` varchar(45) NOT NULL,
  `Werk_idWerk` int(11) DEFAULT NULL,
  `Vervolgstudies_idVervolgstudies` int(11) DEFAULT NULL,
  `Posts_idPosts` int(11) DEFAULT NULL,
  PRIMARY KEY (`idPersonen`),
  KEY `fk_Personen_Werk_idx` (`Werk_idWerk`),
  KEY `fk_Personen_Vervolgstudies1_idx` (`Vervolgstudies_idVervolgstudies`),
  KEY `fk_Personen_Posts1_idx` (`Posts_idPosts`),
  CONSTRAINT `fk_Personen_Posts1` FOREIGN KEY (`Posts_idPosts`) REFERENCES `posts` (`idposts`),
  CONSTRAINT `fk_Personen_Vervolgstudies1` FOREIGN KEY (`Vervolgstudies_idVervolgstudies`) REFERENCES `vervolgstudies` (`idvervolgstudies`),
  CONSTRAINT `fk_Personen_Werk` FOREIGN KEY (`Werk_idWerk`) REFERENCES `werk` (`idwerk`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `personen`
--

LOCK TABLES `personen` WRITE;
/*!40000 ALTER TABLE `personen` DISABLE KEYS */;
INSERT INTO `personen` VALUES (1,'Meltem','Palit','07/02/2000','melltem.palit@gmail.com','+32493883542','2020','IT & Netwerken',NULL,NULL,NULL),(2,'Jasper','De Grauwe','18/01/2000','jasper.degrauwe@gmail.com','+32647588390','2019','IT & Netwerken',NULL,NULL,NULL);
/*!40000 ALTER TABLE `personen` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed on 2018-12-27 18:32:04
-- MySQL dump 10.13  Distrib 8.0.13, for Win64 (x86_64)
--
-- Host: 127.0.0.1    Database: oudleerlingen
-- ------------------------------------------------------
-- Server version	8.0.13

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
 SET NAMES utf8 ;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Table structure for table `posts`
--

DROP TABLE IF EXISTS `posts`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
 SET character_set_client = utf8mb4 ;
CREATE TABLE `posts` (
  `idPosts` int(11) NOT NULL AUTO_INCREMENT,
  `Ervaringen` varchar(280) NOT NULL,
  `Delen` varchar(280) NOT NULL,
  `Herinneringen_SLCB` varchar(280) NOT NULL,
  PRIMARY KEY (`idPosts`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `posts`
--

LOCK TABLES `posts` WRITE;
/*!40000 ALTER TABLE `posts` DISABLE KEYS */;
INSERT INTO `posts` VALUES (1,'Momenteel heb ik geen ervaringen.','DOE JE BEST, DOE JE BEST, BEWIJS NIETS VOOR IEMAND BEWIJS HET VOOR JEZELF!','Mijn eerste dag op Sint-Joris zal ik nooit maar ook nooit vergeten!'),(2,'Momenteel heb ik als ervaring: mijn stage ','DON\'T GIVE UP','De vriendelijke leerkrachten!');
/*!40000 ALTER TABLE `posts` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed on 2018-12-27 18:32:04

-- MySQL dump 10.13  Distrib 8.0.13, for Win64 (x86_64)
--
-- Host: 127.0.0.1    Database: oudleerlingen
-- ------------------------------------------------------
-- Server version	8.0.13

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
 SET NAMES utf8 ;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Dumping events for database 'oudleerlingen'
--

--
-- Dumping routines for database 'oudleerlingen'
--
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed on 2018-12-27 18:32:05

-- MySQL dump 10.13  Distrib 8.0.13, for Win64 (x86_64)
--
-- Host: 127.0.0.1    Database: oudleerlingen
-- ------------------------------------------------------
-- Server version	8.0.13

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
 SET NAMES utf8 ;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Table structure for table `vervolgstudies`
--

DROP TABLE IF EXISTS `vervolgstudies`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
 SET character_set_client = utf8mb4 ;
CREATE TABLE `vervolgstudies` (
  `idVervolgstudies` int(11) NOT NULL AUTO_INCREMENT,
  `School_na_SLCB` varchar(90) NOT NULL,
  `Richting` varchar(45) NOT NULL,
  `Diploma` varchar(45) DEFAULT NULL,
  `Afstudeerjaar` varchar(45) NOT NULL,
  PRIMARY KEY (`idVervolgstudies`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `vervolgstudies`
--

LOCK TABLES `vervolgstudies` WRITE;
/*!40000 ALTER TABLE `vervolgstudies` DISABLE KEYS */;
INSERT INTO `vervolgstudies` VALUES (1,'Odisee Technologie Campus','ICT en electronica','Bachelor','2025'),(2,'KU Leuven','Comics Artist','Bachelor','2024');
/*!40000 ALTER TABLE `vervolgstudies` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed on 2018-12-27 18:32:03
-- MySQL dump 10.13  Distrib 8.0.13, for Win64 (x86_64)
--
-- Host: 127.0.0.1    Database: oudleerlingen
-- ------------------------------------------------------
-- Server version	8.0.13

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
 SET NAMES utf8 ;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Table structure for table `werk`
--

DROP TABLE IF EXISTS `werk`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
 SET character_set_client = utf8mb4 ;
CREATE TABLE `werk` (
  `idWerk` int(11) NOT NULL AUTO_INCREMENT,
  `Werk` varchar(95) NOT NULL,
  `Bedrijf` varchar(95) NOT NULL,
  `Beginjaar` varchar(45) NOT NULL,
  `Vestiging_bedrijf` varchar(45) NOT NULL,
  PRIMARY KEY (`idWerk`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `werk`
--

LOCK TABLES `werk` WRITE;
/*!40000 ALTER TABLE `werk` DISABLE KEYS */;
INSERT INTO `werk` VALUES (1,'App ontwikkelaar','Adobe','2029','Belgie, Antwerpen'),(2,'Comics Designer','Pixar','2030','America, California');
/*!40000 ALTER TABLE `werk` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed on 2018-12-27 18:32:02




